package com.example.sps.activity_recognizer;

public enum SubjectActivity {
    STANDING, WALKING, RUNNING, LOADING, STD_NOT_IDLE, STAIRS, ELEVATOR_UP, ELEVATOR_DOWN, JERKY_MOTION, SIDE_STEPPING_RIGHT, SIDE_STEPPING_LEFT;
}
